### ISSUE TITLE
Pay offline

### ISSUE THREAD

**Issue by Neofliix** [RedAlex/esx_autopaybills#2]
EN: 
Online payments work fine
Offline bill payments don't work

FR: 
Les payements en ligne fonctionne correctement
Les payements des factures hors-ligne ne fonctionne pas

```
[ERROR] [MySQL] [esx_autopaybills] An error happens on MySQL for query "SELECT bank FROM users WHERE identifier = '*****'": ER_BAD_FIELD_ERROR: Champ 'bank' inconnu dans field list
SCRIPT ERROR: @esx_autopaybills/server.lua:60: attempt to compare number with nil
> ref (@esx_autopaybills/server.lua:60)
>  (@mysql-async/mysql-async.js:14959)
```

**Comment by RedAlex** [comment]
Can you show me the table info of your 'users'

**Comment by Neofliix** [comment]
![tempsnip](https://user-images.githubusercontent.com/18237389/76813511-82aabf80-67f8-11ea-82e8-f581043f75ac.png)

**Comment by theorize-hm** [comment]
Hi Alex - es_extended dropped EssentialMode about a month ago and then changed where the player's accounts are saved to the 'accounts' column on the user table.  I am hoping this script can be updated to be used with the latest es_extended as its really a useful script.

**Comment by Neofliix** [comment]
This is the latest version of esx

**Comment by ismaelviac** [comment]
Any fix?

**Comment by ninny2104** [comment]
MySQL.Async.fetchScalar('SELECT accounts FROM users WHERE identifier = @identifier', 
					{
						['@identifier'] = result[i].identifier
					}, function(bankmoney)
						if bankmoney  ~= nil then -- > 0 then --
						--	if math.floor(bankmoney/100*Config.MaxPercentPay) >= result[i].amount then
								MySQL.Sync.execute('UPDATE users SET accounts = accounts - @bank WHERE identifier = @identifier',
								{
									['@bank']       = result[i].amount,
									['@identifier'] = result[i].identifier
								})
								TriggerEvent('esx_addonaccount:getSharedAccount', result[i].target, function(account)
									account.addMoney(result[i].amount)
							
								end)
								MySQL.Sync.execute('DELETE FROM billing WHERE `id` = @id',
								{
									['@id'] = result[i].id
								})
								print(result[i].identifier.." pagare "..(result[i].amount).." una fattura dovuta a "..result[i].target)
							else
								MySQL.Sync.execute('UPDATE users SET accounts = accounts - @bank WHERE identifier = @identifier',
								{
									['@bank']       = math.floor(bankmoney/100*Config.MaxPercentPay),
									['@identifier'] = result[i].identifier
								})
								MySQL.Sync.execute('UPDATE billing SET amount = amount - @amount `id` = @id',
								{
									['@amount']       = math.floor(bankmoney/100*Config.MaxPercentPay),
									['@id'] = result[i].id
								})
								print(result[i].identifier.." pagare "..(math.floor(bankmoney/100*Config.MaxPercentPay)).." una fattura dovuta a "..result[i].target)
							end
						--end
					end)
				end
			end
		end)
	end)
end

**Comment by ninny2104** [comment]
change  server.lua 
MySQL.Sync.execute('UPDATE users SET bank= bank - @bank WHERE identifier = @identifier',
with 
MySQL.Sync.execute('UPDATE users SET accounts = accounts - @bank WHERE identifier = @identifier',

**Comment by ninny2104** [comment]
else -- pay rent either way
					MySQL.Async.fetchScalar('SELECT accounts FROM users WHERE identifier = @identifier', 
					{
						['@identifier'] = result[i].identifier
					}, function(accounts)
						
						if accounts then
							local playerAccounts = json.decode(accounts)
							if playerAccounts and playerAccounts.bank then
								if playerAccounts.bank >= result[i].amount then
									playerAccounts.bank = playerAccounts.bank - result[i].amount
					--	if math.floor(accounts/100*Config.MaxPercentPay) >= result[i].amount then
								MySQL.Sync.execute('UPDATE users SET accounts = @accounts  WHERE identifier = @identifier',
								{
									['@accounts']   = json.encode(playerAccounts),
									['@identifier'] = result[i].identifier
								})
								TriggerEvent('esx_addonaccount:getSharedAccount', result[i].target, function(account)
									account.addMoney(result[i].amount)
							
								end)
								MySQL.Sync.execute('DELETE FROM billing WHERE `id` = @id',
								{
									['@id'] = result[i].id
								})
								print(result[i].identifier.." pagare "..(result[i].amount).." una fattura dovuta a "..result[i].target)
						--else
								--[[MySQL.Sync.execute('UPDATE users SET accounts = @accounts  WHERE identifier = @identifier',
								{
									['@accounts']       = math.floor(accounts/100*Config.MaxPercentPay),
									['@identifier'] = result[i].identifier
								})
								MySQL.Sync.execute('UPDATE billing SET amount = amount - @amount `id` = @id',
								{
									['@amount']       = math.floor(accounts/100*Config.MaxPercentPay),
									['@id'] = result[i].id
								})
								print(result[i].identifier.." pagare "..(math.floor(accounts/100*Config.MaxPercentPay)).." una fattura dovuta a "..result[i].target)--]]
							--end--]]
						end
					end
				end
					end)
				end
			end
		end)
	end)
end

**Comment by xrtw** [comment]
up

**Comment by RedAlex** [comment]
try this and give me news
