### ISSUE TITLE
[REQUEST]Adding the money we pay to the company's money

### ISSUE THREAD

**Issue by ZowK** [RedAlex/esx_autopaybills#4]
I explain myself, I read the code and tested the game, every morning I pay my fines well but the money doesn't go in the company vault. Can we get that into the next release, please? Thanks

ZowK

**Comment by Hallucination61** [comment]
This would be awesome!

**Comment by Bahaamin** [comment]
This would be awesome!

**Comment by RedAlex** [comment]
I have test and work fine
